### ISSUE TITLE
Feedback on landing page

### ISSUE THREAD

**Issue by ifirmawan** [akvo/partos-pat#104]
## TODO/DONE

- [x] Replace "Why use PAT" with new text
- [x] Remove the word "Features" from landing page
- [x] Replace footer of landing page with the same as Partos website
- [x] Add "Power Awareness Tool" underneath logo on login page
